name: first workflow
env:
  WORKFLOW_VAR: "declared on the WORKFLOW level"
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
    - name: firstJob script
      shell: bash
      run: echo Hello World! This is the first job
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: greetings
      id: greetings
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
    - name: time
      run: |
        echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "declared on the JOB level"
    steps:
    - name: secondJob script
      shell: bash
      run: |
        echo this is the second job
        echo and this is a multi-line script
    - name: env vars
      env:
        STEP_VAR: "declared on the STEP level"
      run: |
        echo $WORKFLOW_VAR
        echo $JOB_VAR
        echo $STEP_VAR
        echo "The following is a secret: ${{ secrets.MAIN_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
        echo "The following are default environment variables:"
        echo $GITHUB_ACTOR
        echo $GITHUB_JOB
        echo $GITHUB_REF
